version: "3.8"
services:
  movieworld_app:
    container_name: movieworld_app
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    expose:
      - 9000
    volumes:
      - .:/usr/src/app
      - ./public:/usr/src/app/public
    depends_on:
      - movieworld_db
    restart: always
    networks:
      - app_network

  movieworld_nginx:
    container_name: movieworld_nginx
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    volumes:
      - ./public:/usr/src/app/public
    ports:
      - 8010:80
    depends_on:
      - movieworld_app
    environment:
      NGINX_FPM_HOST: movieworld_app
      NGINX_ROOT: /usr/src/app/public
    restart: always
    networks:
      - app_network

  movieworld_db:
    container_name: movieworld_db
    image: mysql:8.0.20
    restart: always
    volumes:
      - ./storage/db-data:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: ${DB_USERNAME}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    networks:
      - app_network

  # Phpmyadmin Service
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pma_movieworld
    links:
      - movieworld_db
    environment:
      PMA_HOST: ${DB_HOST}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      PMA_PORT: 3306
    restart: always
    ports:
      - 8011:80
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
